name: CI

# Trigger the workflow manually through GitHub Actions
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'TvOS'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Bundler and CocoaPods
      run: |
        gem install bundler
        gem install cocoapods -v 1.8.3
        pod --version  # Verify CocoaPods version

    - name: Install Ruby Gems and CocoaPods Dependencies
      run: |
        bundle install
        bundle exec pod repo update
        bundle exec pod install

    - name: Update Podfile to use specific Reachability commit
      run: |
        sed -i '' -e "s|commit `788111ebf98e86368cd03da17f884015d2fc1543`|tag 'v3.2'|g" Podfile
        cat Podfile

    - name: Clean Build Artifacts
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData

    - name: Set Swift Version
      run: |
        # Update the project files to set the Swift version
        find . -name '*.xcodeproj' -exec sh -c '
          for xcodeproj in "$@"; do
            echo "Setting Swift version in $xcodeproj"
            plutil -replace SwiftVersion -string "5.0" "$xcodeproj/project.pbxproj"
          done' sh {} +

    - name: Actual Build
      run: set -o pipefail && xcodebuild archive -workspace PopcornTime.xcworkspace -scheme PopcornTime -sdk appletvos -configuration Debug clean build CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | tee build.log | xcpretty

    - name: Generate Unsigned Debug IPA
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/*.app ~/Payload/
        zip -r PopcornTimeTV.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'PopcornTimeTV'
        path: ~/PopcornTimeTV.ipa
