name: CI

# Trigger the workflow manually through GitHub Actions
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'TvOS'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Select Latest Xcode
      run: |
        sudo xcode-select -s /Applications/$(ls /Applications | grep -E '^Xcode.*\.app$' | sort -rV | head -n 1)

    - name: use cache
      id: cache
      uses: actions/cache@v2
      with:
        path: Frameworks
        key: ${{ runner.os }}-${{ hashFiles('Podfile') }}-${{ hashFiles('Gemfile') }}

    - name: Update Podfile to use specific Reachability commit
      run: |
        sed -i '' -e "s|commit `788111ebf98e86368cd03da17f884015d2fc1543`|tag 'v3.2'|g" Podfile
        cat Podfile

    - name: Retry Get Dependencies
      run: |
        for i in 1 2 3; do
          if bundle exec pod install; then
            break
          else
            echo "Retrying pod install ($i/3)..."
            sleep 5
          fi
        done

    - name: actual build
      run: set -o pipefail && xcodebuild archive -workspace PopcornTime.xcworkspace -scheme PopcornTimetvOS -sdk appletvos -configuration Debug clean build CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | tee build.log | xcpretty

    - name: generate unsigned debug ipa
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/*.app ~/Payload/
        zip -r PopcornTimeTV.ipa Payload

    - name: upload ipa
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'PopcornTimeTV'
        path: ~/PopcornTimeTV.ipa
